database:
    host: 125.64.33.18
    port: 5432
    user: postgres
    password: s8nu2RF9PdqtQRRB2tHkoELF
    dbname: lotus_car
    sslmode: disable
server:
    address: :8080
deal:
  lotus_path: /Users/max/workspace/filecoin/lotus-optimized/lotus
  boost_path: /Users/max/workspace/filecoin/boost/boost --repo=/Users/max/.boost-client
  deal_delay: 1000  # 发单间隔时间（毫秒）
